//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universal_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class final_View
    {
        public string StateName { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Expr2 { get; set; }
        public string State { get; set; }
        public string DoB { get; set; }
        public string UniqueCode { get; set; }
        public string Date { get; set; }
        public byte[] Image { get; set; }
        public string Password { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public int EmpId { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
    }
}
