//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universal_Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProfessionalDetail_Table
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Employee Code is required.")]
        public string EmployeeCode { get; set; }

        [Required(ErrorMessage = "Employee PF No is required.")]
        public string EmployeePFNo { get; set; }

        [Required(ErrorMessage = "Salary is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "Salary must be a positive number.")]
        public string Salary { get; set; }

        [Required(ErrorMessage = "Marriage Anniversary Date is required.")]
        [DataType(DataType.Date, ErrorMessage = "Please enter a valid date.")]
        public string MarrigeAnniversaryDate { get; set; }
    }
}
